version: '3.3'

services:
  minid-updater:
    image: ${REGISTRY}/minid-updater:${VERSION}
    configs:
      - log_config
    extra_hosts:
      - "eid-elk-app01.dmz.local:10.243.220.21"
    ports:
      - 8080
    networks:
      atest:
    dns: 8.8.8.8
    deploy:
      placement:
        constraints:
          - node.labels.atest == true
  activemq:
    image:  rmohr/activemq:5.11.1
    extra_hosts:
      - "eid-elk-app01.dmz.local:10.243.220.21"
    configs:
      - log_config
    ports:
      - 61717:61616 # Statisk ekstern port pga lokal config har avhengigheit til tjenesten
      - 8161
    networks:
      atest:
    dns: 8.8.8.8
    deploy:
      placement:
        constraints:
          - node.labels.atest == true
  opendj:
    image: eid-jenkins02.dmz.local:8081/opendj:latest
    extra_hosts:
      - "eid-elk-app01.dmz.local:10.243.220.21"
    configs:
      - log_config
    ports:
      - 399:389 # Statisk ekstern port pga lokal config har avhengigheit til tjenesten
    networks:
      atest:
    dns: 8.8.8.8
    deploy:
      placement:
        constraints:
          - node.labels.atest == true
networks:
  atest:
    driver: overlay
    attachable: true
configs:
  log_config:
    file: ./log_config
